# Generated by Django 6.0.5 on 2026-05-31 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='last_done_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
